### PR TITLE
Add 'Date RippleTime' to TxBase

### PR DESCRIPTION
**Pull request by r0bertz**

### CODE REVIEW

**Comment by r0bertz** [comment]
https://github.com/ripple/rippled/search?utf8=%E2%9C%93&q=%22jss%3A%3Adate%22&type=

It appears so. At least we can add it as "omitempty". I will send another PR if that sounds good to you.

**Comment by donovanhide** [comment]
Which API response do you see the `Date` field in?

**Comment by donovanhide** [comment]
Ok, it probably belongs in this struct then:

https://github.com/rubblelabs/ripple/blob/master/websockets/commands.go#L105

**Comment by r0bertz** [comment]
SGTM. Will send another PR.

**Pull request closed without merging**
